import './globals.css'
import type { Metadata } from 'next'
import { Kanit } from 'next/font/google'
 
const kanit = Kanit({ weight: ["100", "200", "400", "600"], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={kanit.className}>
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  )
}
